[package]
name = "@pihub/core"
version = "1.0.0"
resolve_root = "lib/"

[authors]
"Niklas Rosenstein" = { email = "rosensteinniklas@gmail.com" }

[bin]
pihub = "./bin/main"

[dependencies.python]
Flask = ">=0.12.2"
pony = ">=0.7.2"
APScheduler = ">=3.3.1"

[pihub.components]
auth = "./components/auth"
dashboard = "./components/dashboard"
