[package]
name = "@pihub/core"
version = "1.0.0"
resolve_root = "lib/"

[authors]
"Niklas Rosenstein" = { email = "rosensteinniklas@gmail.com" }

[bin]
pihub = "./bin/main"

[dependencies.python]
Flask = ">=0.12.2"
pony = ">=0.7.2"
APScheduler = ">=3.3.1"
pyspeedtest = ">=1.2.7"
plotly = ">=2.1.0"
python-dateutil = ">=2.6.1"
feedparser = ">=5.2.1"

[pihub.components]
auth = "./components/auth"
dashboard = "./components/dashboard"
speedtest = "./components/speedtest"
rss_feeds = "./components/rss_feeds"
duckdns = "./components/duckdns"
